Repository TechnionYP5779/Team5-Fitnesspeaker, pull requests merged in 2019-01, with the labels that each got.

#94 Refactor db
  src/main/java/GraphsMaker/simpleGraph.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/AddBloodPressureIntentHandler.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/AddDrinkIntent.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/AddFoodIntentHandler.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/GetBloodPressureIntentHandler.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/HowManyIDrankIntent.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/SendDailyEmailHandler.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/WeeklyMailReportHandler.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/WeightProgressIntentHandler.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/WhatIAteIntentHandler.java
  src/main/java/Utils/DBUtils.java
  src/main/java/Utils/DailyStatistics.java
  src/main/java/Utils/EmailSender.java
  src/main/java/Utils/WeeklyStatistics.java
  src/test/java/GraphsMaker/simpleGraphTest.java
  src/test/java/Utils/DBUtilsTest.java
  src/test/java/Utils/DailyStatisticsTest.java
  src/test/java/Utils/EmailSenderTest.java
  src/test/java/Utils/WeeklyStatisticsTest.java
Labels: DB, review

#98 Add portion amount option
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/AddFoodIntentHandler.java
  src/main/java/Utils/PortionRequestGen.java
  src/main/java/Utils/WeightConverter.java
  src/test/java/Utils/DBUtilsTest.java
  src/test/java/Utils/PortionRequestGenTest.java
  src/test/java/Utils/WeightConverterTest.java
Labels: review

#108 Intents refactor
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/AddAgeIntentHandler.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/AddHeightIntentHandler.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/AddSmokeIntentHandler.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/BMIIntentHandler.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/GetCigarLimitIntentHandler.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/GetGoalIntentHandler.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/HowMuchCaloriesIntentHandler.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/HowMuchHeightIntent.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/HowMuchSmokedIntentHandler.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/HowOldIntentHandler.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/SetCigarLimitIntentHandler.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/SetGoalIntentHandler.java
Labels: review

#116 Refactor jso nand intents speech
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/AddFoodIntentHandler.java
  src/main/java/Utils/FoodExceptions.java
  src/main/java/Utils/PortionRequestGen.java
  src/main/java/Utils/UnitsConverter.java
  src/main/java/Utils/WeightConverter.java
  src/test/java/Utils/PortionRequestGenTest.java
  src/test/java/Utils/UnitsConverterTest.java
  src/test/java/Utils/VolumeConverterTest.java
  src/test/java/Utils/WeightConverterTest.java
Labels: review

#119 String externalization
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/DrinkAlchoholHandler.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/SendDailyEmailHandler.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/WeeklyMailReportHandler.java
  src/main/java/Utils/Strings.java
Labels: review

#120 Devepintent
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/AddWeightIntentHandler.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/HowMuchWeightIntentHandler.java
Labels: review

#122 Refactored HowMuchCaloriesIntentHandler.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/HowMuchCaloriesIntentHandler.java
Labels: review

#125 Goal progress feature
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/AddAgeIntentHandler.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/AddHeightIntentHandler.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/AddSmokeIntentHandler.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/BMIIntentHandler.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/GetCigarLimitIntentHandler.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/GetGoalIntentHandler.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/HowMuchCaloriesIntentHandler.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/HowMuchHeightIntent.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/HowMuchSmokedIntentHandler.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/HowOldIntentHandler.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/SetCigarLimitIntentHandler.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/SetGoalIntentHandler.java
  src/main/java/Utils/Strings.java
Labels: feature, review

#127 Refactoring
  src/main/java/GraphsMaker/simpleGraph.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/AddWeightGoalIntentHandler.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/CanIDriveIntentHandler.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/PeriodicWeightProgressHandler.java
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/WeightProgressIntentHandler.java
  src/main/java/Utils/AlcoholBloodCalc.java
  src/main/java/Utils/EmailSender.java
Labels: review

#126 Devmeals
  src/main/java/Team5/Fitnesspeaker/AlexaCommunication/Handlers/WhatIAteIntentHandler.java
  src/main/java/Utils/Portion.java
  src/test/java/Utils/PortionTest.java
Labels: review
